// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-OPF4WMjk4MLZURNPWAagB0WSmbc--zo',
    appId: '1:838774403457:web:6c0bed8e32e63379403880',
    messagingSenderId: '838774403457',
    projectId: 'acmproject-practice',
    authDomain: 'acmproject-practice.firebaseapp.com',
    storageBucket: 'acmproject-practice.appspot.com',
    measurementId: 'G-KGY740ZFQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlv_7aLCfuFaxfYIX0tJicObEDcQhaTTY',
    appId: '1:838774403457:android:b7e6c9a1ba7bc1d9403880',
    messagingSenderId: '838774403457',
    projectId: 'acmproject-practice',
    storageBucket: 'acmproject-practice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5wFz-cpUtmlJWZbwbasjk7fdamkPJAIc',
    appId: '1:838774403457:ios:9f71003e8d556ddc403880',
    messagingSenderId: '838774403457',
    projectId: 'acmproject-practice',
    storageBucket: 'acmproject-practice.appspot.com',
    iosClientId: '838774403457-g96lkeefedap1n7r9qpbke4ff44n582b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
