// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3HBdclNzOAMPVciQUiHlKgc11hKMBruo',
    appId: '1:96068490076:web:dccff56fb6e3571c0aa799',
    messagingSenderId: '96068490076',
    projectId: 'ready-pet-go',
    authDomain: 'ready-pet-go.firebaseapp.com',
    storageBucket: 'ready-pet-go.appspot.com',
    measurementId: 'G-SCMTVP6NC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLn_GiYk1CTw8FGWYV8EODSp7jcy0KxCo',
    appId: '1:96068490076:android:b26f65323bc708000aa799',
    messagingSenderId: '96068490076',
    projectId: 'ready-pet-go',
    storageBucket: 'ready-pet-go.appspot.com',
  );
}
